const cards = {
    "andrew":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "austin":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "brent":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "jacob":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "sasha":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "tim":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "trevor":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "will":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ]
}

export default cards;