const cards = {
    "andrew":[
        "Water World (anywhere)",
        ">50% of group is in NYC at same time",
        "Andrew brings a girl to Flatland Calvary 5/4/24",
        "Jacob wear a pair of cowboy boots (in public)",
        "Trevor visits all 4 major metro areas in Texas △ in one weekend",
        "Brent goes 7 consecutive days NOT visiting Apartments.com",
        "Will dates another girl in the \"Greater Beaumont\" area",
        "Tim does a 360 on the wakeboard (need a witness)",
        "Austin ends up on TV",
        "Sasha gets a job in the defense industry",
        "Jacob gets into grad school",
        "Texas baets TAMU in football",
        "Trevor leg injury",
        "Andrew has to travel to Philly",
        "Any person (other than Jacob/Sash) eats a Pasqual's BLT",
        "Everyone attends a hibachi meal at the same time",
        "Will gets a hole in one (golf)",
        "Tim's OKC Thunder win the NBA Championship",
        "Brent sells his Tesla stock",
        "Jacob shaves/loses his beard",
        "Any person sees Dua Lipa in person",
        "Sasha 2nd cat",
        "Austin gets invited to the Hamptons",
        "Any person goes viral on TikTok",
        "Land, water, and sky are simultaneously occupied by group members"
    ],

    "austin":[
        "Andrew to Philly",
        "Tim makes Trevor's parents mad when partying at his house",
        "Competitive video game argument that lasts for longer than an hour",
        "The Hoe dies",
        "New Will blackout drunk photo",
        "Bad/funny first date story",
        "Someone hooks up with someone at a wedding",
        "Andrew uses Italian to get a number/date",
        "Austin jinxes a sports team",
        "Someone screw up their Spotify Wrapped by falling asleep/playign something by accident",
        "Jacob pisses his pants",
        "Election year meme makes it to the Popular tab of The Rave",
        "Brent complaint about something in Denver",
        "A member of the group throws up after getting off the NYC Subway when visiting Austin",
        "3+ people have power go out due to weather in Texas",
        "More than 3 significant others",
        "Jacob makes us all buy a game that we get less than 2 hours of play time on",
        "\"Oh No Digiorno\" A pizza gets dropped or burned on Pizza Night",
        "A member of the group goes MIA for a month or more",
        "Someone hit by car",
        "A member of the group meets a Youtuber/streamer in public, randomly",
        "The group does not play Satisfactory for more than a week (game launches and is played for more than an hour)",
        "Trevor leg injury",
        "Someone gets hurt or burned at the Utah house",
        "Trevor dates someone with a cat"
    ],

    "brent":[
        "Trevor refers to himself as \"The Trevor\" post coitus",
        "Andre tells Elena to fuck off (and blocks her)",
        "Jacob purchases home in New Haven, Connecticut",
        "Jacob gets into screaming match with Will (Overwatch related)",
        "Will gets his time at Port Arthur extended",
        "Emergency room visit (anyone)",
        "Brent eats shit snowboarding or skiing",
        "Austin eats shit on Utah trails",
        "Austin starts playing Destiny 2 again",
        "Brent has car broken into",
        "Tim starts playing rent",
        "Tim gets an Austinite e-girl girlfriend",
        "Waterworld",
        "Sasha buys Brent cigatettes",
        "TAMU beats Texas",
        "Trevor gets mauled by dogs",
        "Andrew gets new PC (or parts in excess of $1000",
        "Will gets promoted at work",
        "Sasha is diagnosed with autism (high functioning)",
        "Parents divorced (anyone)",
        "Jacob sends some dogshit tumblr screenshot in Sasma's",
        "Tim gets roofied with molly (again)",
        "Austin prevents a New York terror attack",
        "Trevor buys 3 or more Mercy skins",
        "Will only sleeps with white women"
    ],

    "jacob":[
        "Tahoe gets totaled",
        "Trevor leg injury",
        "Austin joins NYC area polycule",
        "Brent goth GF",
        "Entry At least 3 simultaneous significant others",
        "Tim passes FE",
        "Andrew apartment waterworld",
        "Will wedding hookup",
        "Sasha strip club visit",
        "NOLA bar fight",
        "Full knee replacement (anyone)",
        "Tim sinks the boat",
        "Trevor schmalds over Mia Zugheri",
        "Thanos snap #3",
        "Will shotgun wedding",
        "Someone detained by police",
        "Austin lands in HOU and immediately requests Cane's",
        "Near death experience on Utah hiking trails",
        "Andrew goes to Philly",
        "Austin gastropub investment",
        "Brent leaks gvmt secrets",
        "Andrew concussion #4",
        "Pizza is dropped in Tim's truck",
        "Trevor hit by car",
        "CS knife unboxing"
    ],

    "sasha":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "tim":[
        "Entry 1",
        "Entry 2",
        "Entry 3",
        "Entry 4",
        "Entry 5",
        "Entry 6",
        "Entry 7",
        "Entry 8",
        "Entry 9",
        "Entry 10",
        "Entry 11",
        "Entry 12",
        "Entry 13",
        "Entry 14",
        "Entry 15",
        "Entry 16",
        "Entry 17",
        "Entry 18",
        "Entry 19",
        "Entry 20",
        "Entry 21",
        "Entry 22",
        "Entry 23",
        "Entry 24",
        "Entry 25"
    ],

    "trevor":[
        "Will gets back into Minecraft speed running",
        "Austin takes off work to play destiny",
        "Brent says something out of pocket to someone our parents age",
        "Jacob buys a large piece of meat (preferably from a pig)",
        "Jacob makes reservations at La Fonda on Main",
        "Brent has sex",
        "Andrew curves a girl who wants to fuck him",
        "Tim gets injured in a rec league game",
        "Will has more than 2 guests in Port Arthur",
        "Sasha makes her family cookie recipe but they don’t come like she expected",
        "The Tahoe needs repair work",
        "Brent discloses NDA/security clearance info",
        "Brent hits a drunk cig then craves nicotine for days",
        "Andrew steps foot on summer camp property",
        "Tim gets a goth gf",
        "Jacob’s mom gets him a blackstone",
        "Austin gets drunk and misses his exit on the subway",
        "Andrew moves to Philly",
        "Sasha causes an accident or nearly causes one while she’s behind the wheel",
        "Will goes to urgent care",
        "Tim goes 30-0 on honzo but they give POTG to someone else who just pressed Q",
        "My parents ask Austin how we know him at the crawfish boil",
        "Andrew’s job tries to fuck him so he gets a new one",
        "Sasha locks Jacob out of the house",
        "Jacob hits someone with his car"
    ],

    "will":[
        "UT vs TAMU games goes to triple overtime",
        "Jacob does not move away from Texas",
        "Tim eats a ghost pepper (preferably on accident but on purpose would count too)",
        "A rat jumps on Austin in the NYC subway",
        "Andrew starts dating a girl who is more than one year older than him",
        "Somebody loses their wallet in NOLA",
        "Somebody loses their passport",
        "Anybody watches Dune 2 other than Brent",
        "Sasha adpots another cat",
        "Somebody has a kitchen fire",
        "Trevor smokes a cigarette (just one drag)",
        "Somebody gets bit by a wild (or untamed) animal",
        "Brent has a cig when drunk",
        "Brent breaks (or fractures) a bone whilst skiing",
        "Austin has to move to a new apartment",
        "Jacob gets more than 12 frags in a game of Counter Strike",
        "Trevor loses a chunk of skin from one of his hands",
        "Somebody shits their pants in their car",
        "Brent accidentally eats an edible in colorado",
        "3+ people in our friend group get laid at the christmas party (Jacob/Sasha only count for one)",
        "Somebody has to purchase a Plan B",
        "Tim loses his virginity",
        "Andrew sleeps with Gloria Gardner",
        "Trevor sleeps with Mia",
        "Will sleeps with Sofia Munoz"
    ]
}

export default cards;